### ISSUE TITLE
Add typescript support for env file.

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#179]
**Is your feature request related to a problem? Please describe.**
env doesn't have typescript support.
I think good idea is add this:

**Describe the solution you'd like**
Add:

```ts
interface ImportMetaEnv {
    readonly __DEV__: string
    readonly __FIREFOX__: string
}
```

to
```
vite-env.d.ts
```

**Comment by Jonghakseo** [comment]
Currently, the __DEV__ and __FIREFOX__ environment variables are not used in the actual source code.
Therefore, we didn't add them to the environment variable types because we didn't think there was any room to reference them via import.meta.env.

Do you mean in case we use those environment variables inside the source code?

**Comment by PatrykKuniczak** [comment]
You right, i think about it yesterday see the mentioned #187 PR :)

**Comment by Jonghakseo** [comment]
@all-contributors please add @PatrykKuniczak for ideas
