### ISSUE TITLE
how can I    import sass in pages/content/components/Demo/app.tsx 

### ISSUE THREAD

**Issue by webLiang** [Jonghakseo/chrome-extension-boilerplate-react-vite#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jonghakseo** [comment]
Maybe you can use this.

### Demo/app.tsx
```tsx
import { useEffect } from "react";
import css from "./app.scss";

export default function App() {
  useEffect(() => {
    console.log("content view loaded");
  }, []);

  return (
    <div className="content-view-scss">
      <style>{css}</style>
      content view
    </div>
  );
}

```

### Demo/app.scss
```scss
.content-view-scss {
  color: red;
}

```

**Comment by PatrykKuniczak** [comment]
@webLiang https://stackoverflow.com/questions/5452957/add-css-to-pages-through-a-css-file

And here you have https://developer.chrome.com/docs/extensions/reference/runtime/#example-get-url


Get url, which are help to import sth inside content script, cause it works in other env and import inside content script, isn't easy as we can think 😁

Let us know if the problem is solved
