### ISSUE TITLE
How to use NextUI with twind?

### ISSUE THREAD

**Issue by lalawila** [Jonghakseo/chrome-extension-boilerplate-react-vite#192]
Nextui can be easy to set up with tailwindcss. But I dont know how to use it with twind. I have tried many way and spent several days in that.

Or can I use nextui with pure tailwindcss in this project? How to do that?

Thank you for your reply!

**Comment by Jonghakseo** [comment]
The underlying problem is probably a bunch of unfamiliarity, as I'm not an advocate for tailwindcss.

**Comment by chamiduu** [comment]
@lalawila Did you manage to setup tailwind with NextUI? I managed to setup tailwind but it looks like the tailwind styles are not being applied to those NextUI components.

**Comment by adasq** [comment]
Had similar issue. The problem was:

As documentation suggests, you should  extend `tailwind.config.js` by adding `"./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"` into `content` array

Given that I extended the config file inside the `@extension/popup` module, `"./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"` was linking to non-existing directory (actually, `@nextui-org` was installed to the root project `node_modules`)

Hence I linked it this way - `"../../node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"`

Works!
