### ISSUE TITLE
manifest.json file listens for compilation issues

### ISSUE THREAD

**Issue by wangxinyugithub** [Jonghakseo/chrome-extension-boilerplate-react-vite#261]
The manifest.ts file has added listening, but the contents modified after starting local development are not updated in the compiled dist file

It is hoped that the contents of the manifest.ts file can be modified during the development process to monitor the simultaneous update of the manifest.json file in the dist file after recompilation

**Comment by PatrykKuniczak** [comment]
@wangxinyugithub We're not listening for files outside of src, but i think also about listening for manifest or other core files.

Are you want to open PR with that change?

**Comment by PatrykKuniczak** [comment]
Now i have a think.

This template is created for solved issue with working on yours plugins, not the core code, manifest is outside of src.

We must think about it, maybe it's good idee.

Let's wait whats @Jonghakseo write :)

**Comment by Jonghakseo** [comment]
I'll delegate the change detection for local files to the filesystem and apply the changes detected by the plugin to the completion of the build. While I'm at it, I'll also look at this issue.

**Comment by Jonghakseo** [comment]
#265 

I was hoping to be able to handle the issue content while doing the above, but it's more complicated than I thought, so I'll cover that separately.

I need to create a new manifest when I change the manifest, which is inconvenient because I have to reimport the changed manifest.ts file, but I think I can do it, just be a bit patient.

**Comment by PatrykKuniczak** [comment]
> * [[Enhance] Modify to let the plugin do the build completion detection not file system. #265](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/265)
> 
> I was hoping to be able to handle the issue content while doing the above, but it's more complicated than I thought, so I'll cover that separately.
> 
> I need to create a new manifest when I change the manifest, which is inconvenient because I have to reimport the changed manifest.ts file, but I think I can do it, just be a bit patient.

As you write, it's not working now, it detect changes in manifest, but after reload the content inside output manifest.json is old

**Comment by Jonghakseo** [comment]
This is a complicated issue. I used dynamic import to re-import the manifest at the end of the build, but the module system recognized it as a cached module already, so the changes to the contents are not reflected.

I should probably replace the manifest file with js (keeping the type as JSDoc) and use require, but that doesn't seem easy since vite already works as an esm. :(

**Comment by Jonghakseo** [comment]
@all-contributors please add @wangxinyugithub  for bug
