### ISSUE TITLE
Extension name and description

### ISSUE THREAD

**Issue by romaindequidt** [Jonghakseo/chrome-extension-boilerplate-react-vite#287]
**Is your feature request related to a problem? Please describe.**
The name of the extention is the name of the package: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/blob/main/manifest.js#L9
Package name regexp is restricted by pattern:  `^(?:(?:@(?:[a-z0-9-*~][a-z0-9-*._~]*)?/[a-z0-9-._~])|[a-z0-9-~])[a-z0-9-._~]*$`
But in réality name is rather a human-readable name (e.g. "MyExtension : best extension ever" , "ExtensionBlack : best ad-blocker in the world"...)
Is the a way to have another package.json field mapped to Extension name.
Or even support multiple languages https://developer.chrome.com/docs/extensions/reference/i18n/#how-to-support-multiple-languages

**Describe the solution you'd like**
In manifest.js, I'd set name and description like this:
```
"name": "__MSG_extensionName__",
"description": "__MSG_extensionDescription__",
"default_locale": "en"
```
and I'd create following files:
- _locales/en/messages.json
with "_locales/en/messages.json" file containing such values:
```
{
  ...
  "extensionName": {
    "message": "Chrome extension boilerplate",
    "description": "Extension name"
  },
  "extensionDescription": {
    "message": "Chrome extension boilerplate with React, Vite & Typescript",
    "description": "Extension description"
  },
  ...
}
```

What do you think about that?
I can do the PR.

Thanks in advance,

**Comment by PatrykKuniczak** [comment]
I'm personally using this feature, cause from this template you don't create lib like this or any other like MUI, Nest or anything.

It's useful IMO.

If you need multiple languages you can use e.g i18next, and use this value from package.json as a key.

**Comment by romaindequidt** [comment]
@Jonghakseo are you interested or I cancel the PR ?

**Comment by Jonghakseo** [comment]
@romaindequidt 

In fact, today is the first time I've seen this offer and PR properly. But I've been thinking about it off and on since it came up.

I was thinking that the field __MSG_extensionName__ seems like a bit of an afterthought for developers who aren't thinking about multilingual support, and that it could be a hindrance to understanding the configuration of the extension.

However, I think it's good that the name of the package is strictly limited by the rules, as you suggested, and the problems I mentioned can be compensated through comments inside the JSON.

I'll do a review on PR, thank you so much for your contribution.
