### ISSUE TITLE
Compile being extremely slow Vite vs Webpack

### ISSUE THREAD

**Issue by hakunin** [Jonghakseo/chrome-extension-boilerplate-react-vite#30]
Hi I moved my project from webpackger based boilerplate to this one using Vite.

I'm also not using Typescript so not sure if this i related, but the compile takes about 8 seconds in dev mode.

It seems to be going over a 1000 files including node modules (although maybe its just checking them).
The project itself has total of 300 js files.

Any ideas what I could try to speed things up?

In contrast, vitest is extremely fast (but possibly due to the dummy test having less dependencies).

**My findings so far:**

According to this page: https://vitejs.dev/guide/dep-pre-bundling.html
Vite should be caching built files in `node_modules/.vite` but no such directory is created in my folder.

So far I see that the build is using a *production build* that has no caching.
I don't mind too much as long as I can work on most of the part of the extension with the normal `vite` command, but I can't yet.

I had to create an `index.html` in the root of the project in order to get the dev server to serve up something, which is useful for quick development.

**Comment by Jonghakseo** [comment]
Chrome extension works by installing through local files, so it is difficult to provide it as a normal dev server. 

I made this boiler plate because I was attracted by the interest and scalability of the vite and rollup ecosystem. 

However, it seems that this boilerplate is not yet capable of providing the optimal build speed.

I've considered many ways, but it's not easy :<

First of all, as for the current issue, I think we can consider using rollup's build cache.

https://rollupjs.org/guide/en/#cache

I will work on improving the build speed using cache this weekend.

**Comment by hakunin** [comment]
That sounds amazing! Let me know when you want me to look at it.

**Comment by Jonghakseo** [comment]
> That sounds amazing! Let me know when you want me to look at it.

I'm sorry, but I've looked at the cache, but there's no progress. I'm going to do something else to fundamentally speed up the development environment. I think this work will take a lot of time, but it may be delayed due to other schedules.

If you can't wait for enough time (approximately 1-2 months), would you consider applying the plug-in below to speed up your development environment?

https://github.com/samrum/vite-plugin-web-extension

**Comment by jordn** [comment]
Just piping in to say thank you @Jonghakseo for the package – this saved me a lot of time on getting started.

My current ~10 second (and growing) HMR build time is slightly annoying and slowing down my iteration time. This isn't something I plan on investing a lot of time trying to improve myself, but if there are some efforts to speed that up I'd be grateful – or if you have some quick fixes now I'd appreciate that too.

**Comment by hakunin** [comment]
> Just piping in to say thank you @Jonghakseo for the package – this saved me a lot of time on getting started.
> 
> My current ~10 second (and growing) HMR build time is slightly annoying and slowing down my iteration time. This isn't something I plan on investing a lot of time trying to improve myself, but if there are some efforts to speed that up I'd be grateful – or if you have some quick fixes now I'd appreciate that too.

Quick fix for me was to use the other package mentioned above.

**Comment by Jonghakseo** [comment]
@jordn @hakunin 

Sorry for the delay in my work. Merged a PR that used rollup cache to speed up builds.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/41

I hope it will be of help.
Happy New Year 🎉

**Comment by jordn** [comment]
Nice – thank you! @Jonghakseo 

that's taken my dev build time to about 1 second. Excellent.

**Comment by Jonghakseo** [comment]
@all-contributors please add @hakunin for ideas, please add @jordn for ideas

**Comment by Jonghakseo** [comment]
@all-contributors please add @jordn for ideas
