### ISSUE TITLE
Building for development

### ISSUE THREAD

**Issue by KristiyanTs** [Jonghakseo/chrome-extension-boilerplate-react-vite#34]
For some reason, even when using `npm run dev`, the terminal says "vite v3.1.3 building for **production**...".

Makes it hard to debug since the error messages are not reported properly.

According to my research, `sourcemap: true` in vite config should do the trick, but doesn't.

Any ideas?

**Comment by Jonghakseo** [comment]
Obviously, we are doing production builds every time, so we are aware of the difficult part to debug.

Currently, there are plans to provide the extension development environment as a vite development environment rather than a build.

However, it is difficult to say exactly when that work will be completed.

Would you like to try this option for debugging for the time being?

```json
    "build": "tsc --noEmit && vite build --mode development",
```

**Comment by KristiyanTs** [comment]
Works, thanks!
