### ISSUE TITLE
Is there any way to use it without Typescript?

### ISSUE THREAD

**Issue by dpw1** [Jonghakseo/chrome-extension-boilerplate-react-vite#42]
Hi, thanks for the great work! I'm not interested in Typescript, can I load it up with only Javascript?

**Comment by Jonghakseo** [comment]
mm... I think you can use it by removing typescript-related dependencies. However, I think it is a waste to give up the main function, such as manifest autocompletion support.

There is also a way to use it like js through some settings in tsconfig.json.

Since TypeScript is used universally in my project, it will take some time and effort to remove all dependencies.
Currently, there are no plans to support the JS version. 😢
