### ISSUE TITLE
Can't load content scripts in FireFox

### ISSUE THREAD

**Issue by moritzstingl65** [Jonghakseo/chrome-extension-boilerplate-react-vite#470]
**Describe the bug**
In FireFox content and content-ui cant be loaded

**To Reproduce**
1.  run pnpm dev:firefox
2. Open about:debugging#/runtime/this-firefox and Load the temporary Add-on
3. Go to any website and give the extension permission to read and change data
4. Open console and see errors (see screenshot)

**Expected behavior**
The content scripts should load

**Screenshots**
![content_scripts_errors](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/95340205/4f5ef506-a0a2-41c0-9368-7be35c74da1b)

**Desktop:**
 - OS: Windows 11
 - Browser: FireFox
 - Node Version 20.12.2

**Comment by PatrykKuniczak** [comment]
That's something with messaging i think so.

I spend 2 hours and i still can't solve it.

But here's link to stack:
https://stackoverflow.com/questions/9515704/access-variables-and-functions-defined-in-page-context-from-an-extension/9517879#9517879

Maybe you will find solution

**Comment by govza** [comment]
Needed to replace in manifest.js to make it work
```js
 content_scripts: [
      {
        matches: ['http://*/*', 'https://*/*', '<all_urls>'],
        js: ['content/index.iife_dev.js'],
      },
      {
        matches: ['http://*/*', 'https://*/*', '<all_urls>'],
        js: ['content-ui/index.iife_dev.js'],
      },
      {
        matches: ['http://*/*', 'https://*/*', '<all_urls>'],
        css: ['content.css'], // public folder
      },
    ],
```

**Comment by PatrykKuniczak** [comment]
@govza 

i have that with your approach
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/9de1dfab-f312-4b05-9818-2b59daf2afc3)

Other errors, but still xD

Overall the .dev file was imported by index.iife.js
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/64608510/ed34f08f-073c-43de-b9bb-07bfe1cfbda8)

The problem is located in other place IMO

**Comment by Jonghakseo** [comment]
I'm gonna reproduce in my local env.
