### ISSUE TITLE
.prettierignore is not applied into whole packages

### ISSUE THREAD

**Issue by wonkyDD** [Jonghakseo/chrome-extension-boilerplate-react-vite#514]
**Describe the bug**

`pnpm prettier` is formatting all files without ignoring the files specified in the `.prettierignore` file.
I tried changing `dist` in the prettierignore to `**/dist/`, but it still checks during the formatting stage.

**To Reproduce**

1. `git clone`
2. Run `pnpm dev` to check whether prettier formats `dist` folders
3. Run `pnpm prettier`

**Expected behavior**

When running the `pnpm prettier` command,
it should not check files specified in the `.prettierignore`, including build outputs like dist or build files.

**Screenshots**

It only ignores `dist` folder located in project root.

- `dev-utils` package

<img width="426" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/9fb34416-d7cb-43e0-adbb-ea6409495726">

- `hmr` package

<img width="524" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/def4feb4-a31b-448d-9651-d96c4d4a076c">

- `shared` package

<img width="420" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/79c5234c-0a14-4827-85ab-d49023ca6972">

- `storage` package

<img width="410" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/81248624/334a122c-1b25-479f-8e56-d82ebafb7edd">

**Desktop**

 - OS: macOS Sonoma 14.2.1
 - Node Version v20.11.1

**Comment by PatrykKuniczak** [comment]
@wonkyDD That's because turbo command run scripts for each module independly, now i fix it in #517 but the .prettierignore should be split to several smaller like there's with tsconfig, you know .base.prettierignore and etc.

You can do it with #515
But concating it couldn't be that easy, because of this is not .json
But keep in mind you can specify many paths for --ignore-path, there you can specify this .base.prettierignore and then if devs need to create .prettierignore for 1 package, then he can easly create that file and add it to the script in package.json.
But, (next but XD, good that don't 'butt') don't forget to document it in README.md, to be sure devs know how to manage that.
