### ISSUE TITLE
Add Template Folder with Starter Projects for Advanced Development

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#560]
Integrating monorepo and Turbo technologies provides a powerful toolchain for advanced developers, especially when creating complex browser extensions. 

These users prefer the flexibility and control offered by monorepo over simpler, out-of-the-box solutions like Plasmo and WXT.

I propose adding a `template` folder to the project. This folder would contain a variety of starter projects, making it easier for developers to use their preferred tech stacks. For example, we could include templates like:
- Vue3 for building popup interfaces
- Svelte for developing content.js projects

This addition would greatly attract our target user base, who are primarily advanced developers.

With these templates, developers can easily create new pages in the repository using their favorite technology stack. The command for generating a new workspace would look like this:

```
turbo gen workspace --name popup-vitesse --copy https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/template/popup-vue
```

**Comment by Leizhenpeng** [comment]
If you are willing to introduce this issue proposal, I am very willing to open PR to contribute.

(: In fact, I have already completed the demo of vue3

**Comment by Jonghakseo** [comment]
> If you are willing to introduce this issue proposal, I am very willing to open PR to contribute.
> 
> (: In fact, I have already completed the demo of vue3

Very good, I think your suggestions will help a lot of people!

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng This closing also #524 ?

Overall, i propose to don't add this feature now, let's wait some time, after we create a plan for big refactor, and there we want to create small packages like NestJS have.

Then with e.g this generator people can download additional packages it they need to the core code base, we're need to simplify this template, by adding tools which improve and simplify using of this template, because now when somebody want to add next feature it's a little complicated.

Maybe you have other idea, then i'm not against this feature :)
Keep pushing 🫸

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng Are you working on this?

**Comment by Leizhenpeng** [comment]
Not yet, when we clone this reponow, we will clone all the warehouses, but the version I prefer is that we will have some demo in the other warehouse, and the two warehouses are separated,

because in this way, users only use one warehouse of the smallest mvp for customers, while the other warehouse is full of er, er, template

**Comment by Leizhenpeng** [comment]
@PatrykKuniczak

**Comment by PatrykKuniczak** [comment]
> template

I don't understand what you have wanted to explain 😁

**Comment by PatrykKuniczak** [comment]
@Leizhenpeng Are you want to move forward with this?

**Comment by PatrykKuniczak** [comment]
But this should be implemented just during module split refactor.

Because we need to find solution to create a menu on CLI, like e.g `Vite` have.
Then for each option, we can give users option for select packages what they want.

I mean if user select `Yes` for `content-ui` after this should have next questions about: `Are you want tailwind` `... example components` and etc.

**Comment by PatrykKuniczak** [comment]
We've decided to not implement other frameworks than react on team meeting
