### ISSUE TITLE
Proposal for Simplifying Updates to Old Browser Extension Projects

### ISSUE THREAD

**Issue by Leizhenpeng** [Jonghakseo/chrome-extension-boilerplate-react-vite#607]
### Problem:
Our repository has been used to develop many browser plugins. However, as the repository is updated, it becomes challenging to apply these updates to older projects. These changes are often extensive and can be disruptive to multiple repositories.

### Proposed Solution:
I propose a more efficient update mechanism by publishing packages to npm under the `package` directory. By treating these as dependencies, we can update the packages more easily. This approach offers several benefits:
1. **Simplified Updates:** Users only need to update the relevant packages, making the process smoother, especially for older projects.
2. **Convenient Template Initialization:** We can provide a quick-start template folder, reducing the need for users to install every `package `in the monorepo. They only need to include the essential configurations and their custom  `pages`.

### Benefits:
- **User Convenience:** Especially beneficial for older projects, users can more easily integrate updates without major disruptions.
- **Efficiency:** Streamlines the update process, allowing users to focus on essential configurations and customizations.

**Comment by Leizhenpeng** [comment]
@Jonghakseo

**Comment by PatrykKuniczak** [comment]
But this is a template, not a package like e.g ```turbo```
This is sth like ```NextJS``` you can update Next, but new features are available and you need to use it.

We're creating new folder structure because of new modules and etc.
And this is tricky to implement it to the users, because we don't know what project structure users have.

And There's so many conflicts, because user decide to remove ```content``` and the content is still in the latest version, when user update it, then this folder return to his project, and if he change names of folder, the update is totally unable to do, 
because all folders from template will be downloaded to his project, and he/she will have 2 versions of template in 2 project.

They need to follow only us folder structure, and this need to be defined by us of course, and there's no flexibility for users.

I think this update engine could be a monster, because of the files which user have already on his/her project.

This is not that easy, as update Next, and have new features.

But this idea of the separated packages like e.g ```NestJS``` have is good idea, and i was talking about that with @Jonghakseo several weeks ago.

Maybe i don't see sth, and it's able to implement this, but i don't seen it before in other templates.

**Comment by Leizhenpeng** [comment]
Thx , got it ..

**Comment by wonkyDD** [comment]
If this is achieved, it would be incredibly convenient 👍

**Comment by Jonghakseo** [comment]
As @PatrykKuniczak said, feature-specific management via npm packages would be a huge benefit, maybe we could separate the abstracted VITE settings, HMR modules, etc. into packages for better update benefits. I think it's a good direction to think about, and I'm planning to open a discord community in August, so we can discuss it further there.

Whatever it is, if it helps people developing Chrome extensions, I think it's worth it. 😄

**Comment by PatrykKuniczak** [comment]
@Jonghakseo We achived 2k stars on repo, well done for every contributor ❤

**Comment by PatrykKuniczak** [comment]
I closing this, it will be implemented in the near future.
We will be keeping it in mind, and we will implement in #400 (This attachment have became an notification)
