### ISSUE TITLE
Request for Enhanced Documentation

### ISSUE THREAD

**Issue by VladimirBlagojevic** [Jonghakseo/chrome-extension-boilerplate-react-vite#618]
Hello,

First, I want to thank you for creating this Chrome extension boilerplate. The structure and features are well thought out and will significantly streamline my development process.

However, I have noticed that the boilerplate assumes a level of familiarity with Chrome extension development that some users, including myself, may not possess. The lack of comprehensive documentation can make it challenging for newcomers to fully leverage the capabilities of the boilerplate.

**Comment by PatrykKuniczak** [comment]
@VladimirBlagojevic We will do a better docs for template in the future, because we planning big refactor.

But the lack of knowledge about chrome extensions itself is not our problem.

We can help with template specified problems, because it's quite complicated.

But basic knowledge of React and chrome extension you as a user need to have before 😄 

Let's take a look to: https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/482#issuecomment-2132202739

Because It's duplicated issue

**Comment by Jonghakseo** [comment]
@VladimirBlagojevic 

There's a lot of feedback that we need a tutorial on how to create chrome extensions using this repository. I'll think about how to enrich the documentation, possibly adding it to each package inside the codebase. Thanks for the great suggestion. :)
