### ISSUE TITLE
base.package.json for simplify package.json in all modules (DRY)

### ISSUE THREAD

**Issue by PatrykKuniczak** [Jonghakseo/chrome-extension-boilerplate-react-vite#625]
**Is your feature request related to a problem? Please describe.**
I want to create ```base.package.json``` which will have all props which are redundant for all ```package.json``` in modules/packages, which will implement it and extend on they needs, sth. like we have with ```tsconfig``` and ```tailwind-config```.

What do you think about it @Jonghakseo ?

**Describe the solution you'd like**
Use this package:
https://github.com/microsoft/package-inherit

**Describe alternatives you've considered**
We can do it by ourself, but if there's package from Microsoft, i think it's good idea to use it.

**Comment by Jonghakseo** [comment]
🤔 

I think that the `package.json` file is the entry point to know information about the package and the total set of dependencies. I have some skepticism about creating an additional layer of dependencies in this file.

Also, the problem that the introduced library is trying to solve is `phantom dependencies`, and this problem seems to be solved in the `pnpm`(moving dependency declarations up to package.json in the root path).

**Comment by PatrykKuniczak** [comment]
@Jonghakseo We have almost the same scripts across packages, i think it could be good idea, to create it in one place, let's think about it in that way.

**Comment by Jonghakseo** [comment]
I don't think the structure of using that library for reuse in scripts is common, and I think it may increase the learning curve. 

Do you have any projects I can refer to?

**Comment by PatrykKuniczak** [comment]
@Jonghakseo I haven't seen any project with this approach, this is suggestion, because i see a lot of duplication in scripts.

Let me know, if you are eager to move forward with this 😄

**Comment by PatrykKuniczak** [comment]
@Jonghakseo What's about this?

**Comment by tngflx** [comment]
Hi bro :)
