### ISSUE TITLE
Reload server disconnecting due to insecure web socket connection to local host

### ISSUE THREAD

**Issue by paularah** [Jonghakseo/chrome-extension-boilerplate-react-vite#95]
![Screenshot from 2023-04-21 00-02-53](https://user-images.githubusercontent.com/37967706/233497205-dbe85fa2-ebd4-4c42-b585-4bdc5420a2b3.png)

I know Chrome doesn't allow insecure ws connection to localhost, and that's failing the reload server. Is there something you do differently?

**Comment by Jonghakseo** [comment]
It appears that the error is caused by an issue with wss not running properly in the local development environment. It seems unrelated to Chrome's allow/block policy. Please check if the 'yarn dev' command has been executed properly and try reloading the extension. If it still doesn't work, please provide additional information about the execution context.

**Comment by sumsalabim** [comment]
I'm facing the same issue, 0 errors while running yarn dev
![image](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/37812273/77e07166-ed7b-4a21-94df-29c25960144f)

**Comment by Jonghakseo** [comment]
Please check if the WebSocket server is properly running on your local machine.

**Comment by AriPerkkio** [comment]
I also ran into this, and after 2 hours of debugging I realized this was caused by Brave Browser's privacy settings. Disabling the Shields feature was enough to make websocket connections work.

**Comment by paularah** [comment]
I use Brave browser too, so this is probably the cause for me too. @Jonghakseo I am closing this issue.
